name: Deploy Python Package to PyPI & update docs

on:
  push:

jobs:
  build-package-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Install dependencies for EPL
        working-directory: ./epl-board
        run: |
          python -m pip install --upgrade pip 
          pip install build twine

      - name: Build package
        working-directory: ./epl-board
        run: |
          python -m build --outdir dist/
          twine check --strict dist/*
      
      - name: Install dependencies for E-Commerce
        working-directory: ./ecommerce-website-django
        run: |
          python -m pip install --upgrade pip 
          pip install build twine
      
      - name: Build package
        working-directory: ./ecommerce-website-django
        run: |
          python -m build --outdir dist/
          twine check --strict dist/*

      - name: Publish package
        uses: pypa/gh-action-pypi-publish@v1.8.1
        with:
          user: __token__
          password: ${{ secrets.PYPI_TOKEN }}
          packages: |
            ./epl-board/dist/epl_boardx-*
            ./ecommerce-website-django/dist/ecommerce_website_djangox-*
          verbose: true
