name: Build Python Package

on: release

jobs:
  changedetector:
    runs-on: ubuntu-latest
    # Required permissions
    permissions:
      pull-requests: read
    # Set job outputs to values from filter step
    outputs:
      epl: ${{ steps.filter.outputs.epl1 }}
      ecom: ${{ steps.filter.outputs.ecom1 }}
    steps:
      - uses: actions/checkout@v3
    # For pull requests it's not necessary to checkout the code
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            epl1:
              - 'epl-board/**'
            ecom1:
              - 'ecommerce-website-django/**'

  build-it-epl:
    needs: changedetector
    if: ${{ needs.changedetector.outputs.epl == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip 
          pip install build twine
      - name: Build package for epl
        working-directory: ./ecommerce-website-django
        run: |
          python -m build 
          twine check --strict ./dist/*

  buit-it-eccomerce:
    needs: changedetector
    if: ${{ needs.changedetector.outputs.ecom == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip 
          pip install build twine
      - name: Build package for ecommernce
        working-directory: ./ecommerce-website-django
        run: |
          python -m build 
          twine check --strict ./dist/*
