name: Deploy Python Package to PyPI & update docs

on:
  release:
    types: [published]

jobs:
  build:
    # strategy:
    #   matrix:
    #     directory: ['./ecommerce-website-django','./epl-board']
    name: build-scan-publish
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip 
          pip install build twine
          pwd
          ls
      
      - name: Build package
        working-directory: ./ecommerce-website-django
        run: |
          python -m build --outdir ../dist/
          twine check --strict ../dist/*
          pwd
          ls
      - name: Build package
        working-directory: ./epl-board
        run: |
          python -m build --outdir ../dist/
          twine check --strict ../dist/*
          pwd
          ls
      - name: Scan for vulnerabilities
        run: |
          wget https://github.com/google/osv-scanner/releases/download/v1.2.0/osv-scanner_1.2.0_linux_amd64
          chmod +x ./osv-scanner_1.2.0_linux_amd64
          ./osv-scanner_1.2.0_linux_amd64 --format markdown -r .
        continue-on-error: true
      - name: Publish package
        uses: pypa/gh-action-pypi-publish@v1.8.1
        with:
          user: __token__
          password: ${{ secrets.PYPI_TOKEN }}
          verbose: true
