name: Deploy Python Package to PyPI & update docs

on:
  push:

jobs:
  build-wheels-N-package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Install dependencies for EPL
        working-directory: ./
        run: |
          python -m pip install --upgrade pip 
          pip install build twine

      - name: Build package
        working-directory: ./
        run: |
          python -m build
          twine check --strict dist/*
      
      - name: Install dependencies for E-Commerce
        working-directory: ./ecommerce-website-django
        run: |
          python -m pip install --upgrade pip 
          pip install build twine
      
      - name: Build package
        working-directory: ./ecommerce-website-django
        run: |
          python -m build
          twine check --strict dist/*
