name: Deploy Python Package to PyPI & update docs

on:
  push:

jobs:
  build-wheels-N-package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Dependent Issues
        uses: z0al/dependent-issues@v1.5.2
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip 
          pip install build twine
      - name: Build package
        run: |
          python -m build
          twine check --strict dist/*