name: OSV Scanner

on: push

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: OSV Scanner
        run: |
          docker run -it -v ${PWD}:/src ghcr.io/google/osv-scanner -r .
        continue-on-error: true
