name: OSV Scanner

on: push
  # schedule:
  #   - cron: '0 0 1 * *'

jobs:
  scan:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/google/osv-scanner:latest
    steps:
      - name: OSV Scanner
        run: |
          pwd
          #osv-scanner --format markdown -r . | grep -vE '^((Scanning|Scanned).*)$' > VULNERABILITY.md
        continue-on-error: true
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@gmail.com>
          signoff: true
          title: Add vulnerability report
          commit-message: Add vulnerability report
          body: |
            *Update Vulnerablity report*
          delete-branch: true
          labels: enhancement
          assignees: Kshitiz-Mhto
          reviewers: Kshitiz-Mhto
          draft: false

           
